### ISSUE TITLE
Extend contents file path in merger

### ISSUE THREAD

**Issue by BabelDev0** [BabelDev0/writeme#28]
show the entire file path for the contents in the merger, otherwise, with projects having more than one config file of the same type(e.g. more than one package.json) it is not clear where they come from

![Screenshot 2023-05-22 at 14 19 35](https://github.com/BabelDev0/writeme/assets/91274142/931c165c-ad70-448b-a0b7-3a68f58f7041)

**Comment by ilcors-dev** [comment]
i was having the doubt while implementing it 👍🏼
