### ISSUE TITLE
duplicate section?

### ISSUE THREAD

**Issue by ilcors-dev** [BabelDev0/writeme#30]
currently the generated README.md file lists the technologies used both in the readme title and in the section `built using`, is it necessary to have such kind of duplication?

![image](https://github.com/BabelDev0/writeme/assets/61411878/323248e3-40cf-46df-99cd-a2a2d7dbd399)

and

![image](https://github.com/BabelDev0/writeme/assets/61411878/c9c70209-f953-48f5-abd5-3bc0610dcf18)

**Comment by BabelDev0** [comment]
3089d10f20ae87196a507cb07bc7c866d9c2f3a2
