### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by BabelDev0** [BabelDev0/writeme#33]
We made a program to write README and then ours is not clear, CHE VERGOGNA!
<img width="238" alt="Screenshot 2023-05-23 at 19 46 25" src="https://github.com/BabelDev0/writeme/assets/91274142/231b78e6-9480-4a6c-8f9c-7d4a87eff988">

**Comment by BabelDev0** [comment]
Tell me what you think bout the new README

**Comment by ilcors-dev** [comment]
good & clean
